apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pushover-credentials-sealedsecret.yaml
  - ts-alertmanager.yaml
  - ts-prometheus.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: 'https://prometheus-community.github.io/helm-charts'
    version: 57.2.0 # Replace with the latest stable chart version
    releaseName: kube-prometheus-stack
    namespace: monitoring
    includeCRDs: true
    valuesFile: values.yaml
