---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pushover-credentials
  namespace: monitoring
spec:
  encryptedData:
    token: AgCiF0apnxcvmOr3K02NIDknNs6ZfAaRA5XfnXZc6Cw8kXAjPULyAxWdpXZmupc/LxRoJrRRMrvosGDAH6r7MS8CZKB0MIbOcAXWEy242UAOmMPxB61suop6vJn1HPjF1qTj+JO/puoR9lDzJ6SMR0OJQD4u2OzjSQHgaKqQi//eO0BuXWJvd1u3tLdF5rwwm+J+ij75guhL5Y+76CkbykbNZmgpXvbS5glgp1gykqBb24Euz6ODeLUl0EKZc5K1jBcBVJXhSPxQra4nGlr0J043HWpLa6EmtmeMU5lAXeSHr9UquIUaRGlPf8Okknf2GISrb5TrbwwLW8JDZWDS3tQ9Tb/V2/N5fHuSHfyoBBDFSXgONkyLvnxELCD5jGOXQOpr+AAX0FM7iBgEDDmZNAtibVIZx7GSOJT8FPOPAz4u8IVqlt/vfM9GF1LFxwLH/y/w23UWj8Ftb9SmuE9+fmGxweaEpFNI4UMofKzK12fnZ0ZgYtM2Tppw8f5UpBEKO72MVj42gY7LvFY3Ucy2/qNcixF+mVQG2g3i42xCe7RkZrJA6hkpcffyXYBAivQOwTUpdqzr9VWjhAGE3I1bdguVpaSduOkkshznf6AFUTbp63eM0zY2CG5QEzIB4hDADIJbGnPAA1xwQJPOkCknMvKQxvstcIP2EYkkx1OVFPhQ/Brzy0y7ZbfIY2D7Qo50Ed0aFIi42h4Kbk58BZ/FFlvaNBBqyGM0i4/cY9WNKLw=
    user_key: AgAlo63G5KOuVsSab47P5RjpK845uTxSArgVRQfe0Z2dcOKi+6MF20y+NbrxtqcVEtSZM01uAC1TMFjQJv4CMX9K1KKDf/o/UuKa0Iu4auatb6Gw+xBXdZ3AOGGrVVSQaYufEQJWKZs5JwyBdLvQaINHVBmXKEeiE8cWeQZ1wa/swpFIHcnViUp6POh/VpOnhNX01nfqCIlA5s573ovmnPlFXHD4XvbxqCWUs5gWCnJWlSNj4Ow2pJ0fMUQG19qo+BU1kxo9jeOlqRpfnG0MFhrNQOwfbmNl/p1mFwdPGnEszU1qlmMu1MX8RJU6uV9x6GyjU/Wd2fjpKJmjO0czgeGTtlysPVQic1MhfA09kycVn/LMyP+SZSE5gvDwoeBB7vbHF9GcTLU4aXTcOw07e+b7/GjbAjf8xigSqR2m9A6UwwLAxa83+6HTqAaDDMH8YkIL5V33YUDtU0Z4912aySJsgoJJE5koaXRi3KPa7FYfdR/6XlOILiRY4O8SntIDuJnV/K68K1bX6PUBOYAy0FaioxVGodT1T/hQ0qixo7zLUxUCucPwS9F9qLNV2KIsp5TLs8WA5SVjkDX0Qc8etnLTqdnIRy0d0AcK6Y4jRfBF3LOHXNYXCONXRFN+kbGwWy0hvhf8H6D9BOTMnLXxi7uXnHNlI5Pi7yeHldWVVJL4iNiNhwhvoy4yFZ2OMsyB6+ctpGQBzCfGEJGu1y8J1us3Fzf4VQjkvC3hRG1XegA=
  template:
    metadata:
      name: pushover-credentials
      namespace: monitoring
