---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCDhph6yESgy3gbZByYsxtgDdpLcWUkVZayv3M44lxBISFzXFZ5w5T6Yldg0ojBxUqb+99jcaIbvqvH1Cy7/X17SDJOYb13rPQMaq47eXLIyZaY7gOu5Y1IrqiG7f4NTiWSXFwClri2iPUE0euNJpnAHv0ppIBH2UGGEeAVxvbWx8oUsXXizOwOpSy8zHcWKH1znScg84stC814ts1VQJCWkCiea/zGrdUvF3p2esVKmevC0pAhXkYTfkroWUciZ7C6wRjoU8z/IB2HZ3XgOiapH+PZw28LbfJve69MGmfqvkr99rtBu8dmA8LKeJ5gjZRdXqgpk1G6gBzhvHOi9LAJqBK+SXP8zyx8AgybT70jIs6GIhtHqSynSlb5FEaItKLZEONSSupJ1vrGcnSNSdtaaPf771y8Lou2Z+hcz0h6Cbmm+5Disakwi2XDYUItlZM1pBJMaBb0CrxSwfSPsaNxuvHBhq56adrEjV5hhWvl7+2bgOgJsNvNqm3cSFycTs4Mf6KRgm0tgA5b1m/Y07NorozNz9ysbLMYD/w69kZsZjB1qhaPjxSBjuu8jTvR0Gslkk0069ZidsLa87vjLlf3TTzkwJakO0hVKnctXnkak8obEf7cED6KY1J1SEbX0Li8ET43UbT7Vt21yUeS4rJWuJmMhUdX9RpRS0tD7EfldVYgLJayjN23RFw6sOk3+kgynvAYofvuvY0Tmsge2kgjYA==
    client_secret: AgCH9/heY9jAbfYzFWfSDhZQkNgFVfhrGY1S+Ypq4ZDOrnqWWbqWEsVb0I4Asx2Jympm+okDZojKU4Zm5OpD3QHBG9qlXEYLv18KCY/P1MR6S001ZoThE2G0kp50aJSS3LIDJBl2Ow6EGWYdZisYB7UZCJTqlFUmmlu7q471rzU8O+RLpCR6g3b9U/s386e70iZ0gzZD8pRecBJ/7KfPohv10/OzKgMDFWOQXbODU15g6d1AneyrmXZIwj7CU8FMYuwms2pj43wDBs2ljyB7AwZszo1Ft+gHe3skz+u6C60+9pTxyQj6kh9SvZa7HswwHPjSyt4logPaeWq+ERVUFwBHWrPFTqVdRQcrSWubIZ+LlEQ4UW74/W5S54UFLcr/WfKlCB2sUWAajFZDTdYflh/4Yp0WgrySsZCl7iMEX1AsA/zzXy6wLj5Y2+XIBJ/cHhK2M/p9RKpkfbqpAJ1xedsjov/YCNFIEaa5QMK5dBlNqKhnx29qaVDM7zUKuJBHwB5ncp8hjMn4QXkuZUB9ZoepJOkwhyUq+mkhUr5yEYR1krZtX7PziVemhHelsymJWrMXxbSul8byy/4aCldQx7GXa2XJFP5TqIahLglbivKPeJ/O4RwxOWPdoVjA5Y88L71y8MF+S467ho8rEiBATqsrfBy1BcbNppAs+1/On03ZZPk/c6HFrLLRHhPEgY2lmslbUmsrwP/UMkYL3kSv5qbwf2N/VNmR/uxqEbxo8gvA9S/P0cLAzdHPSz8GFzX03oqSbGmKCFtst1tvZN22dz4=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
