---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgDANPcdH87aUFOXC46Epe8+UU22j63IqMXv69GClOqNj5SuzRMkQv47MB9E3YLPvYO9cH7IGmAh4vVDVMwb6slT8e0thbqXudUY5P+flKkNWOqCvfZ0oDChn6ITZyUmw14wD2QM13NCzOISzvnWaKG3vipdp5JyhIJ7uWosya6jcp26ZDXj/TjNVskGec4wz7DIUvNM5bj/++7P9HHaCiAZeMhMzhq8zBeLyqesVRZ7VwvF+5CKoFj73ZrAAU0nJChwvtmEK1OJ0izmC9AxyybnpepdB5u7YST5AaCaP2GCXI3YvEOe6DyMHUQNDs/f+s1sHI6TrvkWlV1TQ/znI8lZ541nga2FqImmB6XBWFN70XepIOA+Zyo/KSxCMO0/wCHWwQEMOU2C97CfY7vJvLCST3YFFNwDVYnHuEvioi/jb/y3qXm3bMVq7P6MG9ZlDVjht7ClrJZKW0kn2J66fu/yTG4uNW70XMVq6A+eDjNDosbZwYtr/XaTBR/GfKKsnpDRQf+qmCFYq17X/PSE1HJhGnL2KLySBr7zcH8VdOINaXF49Gyr03MD+MCvdnayGdoq8HGN1oOgbdQYZ8t1gyZ3/Fd+U7PtqHkjAAnEJ21Ma4+vV/2HIR1WZz4RIs5kYKzRn/zPOz4B9R85RrF/AmJjR84kXWZ7gIKf6IrMq3E4nW7gzFlH1G20tapuj84RjvpyPHuC7h/u9p13czZrppS8RA==
    clientSecret: AgCBNzyVwo2MFvKUt/uAsigVbMVK4PjV2QcvY+abT7lfwF8x/huuhnypR91uIJcExv/ZI1B/gFlEuZ/u42t8b1hqhnfpqzMw2xwCpvxAjYuDjD/I2VJW1W4t7LdgTDLRBj9DkFcQq2Gn+HUH0nM3lIbCH1+eEKwCKYYhl38sm+NV9OX/jVCDyyCaKZqekp90nGvXo+gbo+d00uWPMpwVqV7hv5/Vwo+XECslAxwMNMQEhE8a7meFLOQ5awXjmA0MNCRS0+hwkRmjGfvwOS3Is4bFQ9Gcz2FU+Zj52mxIlw3/o+OCDH27GQiwb7bbbAIzVNahGFik56LWrtaZc7PFzjj2SJMNvykBoMpa6G416mP2ZNUjQmKiTMUVHWPksipK4XPiqFc6tUSSUtpCOi0ZIt7TH/lOTGc19J26/N5rIHXvhlsPNadnWtfLMm7lWGJusFgYt3ysUWscJMy4vCBpEOSNwi9m+BV660I75fYHf4pXbVXD7Z8qv9oBpWOSeaXGM/vxoOIT5+ZVwhc1EORKvnaSOJ/t0lpBRxs8Qe3g1q7YD1CGJpq+0WedfOnOTTpjC8hKEjXustgDsCpNd7UusNDm0u5mHen2ouZojuiIkNxzRrHh+Fm91LWyeLvyxBNQyF2WJE72/x1ewxCodIjE9P+n/t8A87PAjHAhd5lPErNo/9Z5H3s6sDX/1Aw4s89fOUVyHtgwdHeeli3xXHriwbB1ewE/0wuoD29dB9stntY6ZXnnAhkwGc/ixx/yH8ptvkh04FgTBOQUlRbJDr96VXs=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
