---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synology-csi
  namespace: csi
spec:
  encryptedData:
    client-info.yaml: AgCUu4dj4KXXT35Z7mq8dnZbDaZDDkQMVQ+iJSDqi8u5E8AakQQjPDu+s/2PI2PLTv5rZICvrKDhdbGdoGrVlINuED/s7QA8OtYKqfopgBnraq4/a1FB7kw+JoEWfc6FJX4/EpFLi39306MCRKAFM5Qvh4A5YjHsr9MXeSQfa4BkzPx8sQuvZhcvQ5Lp3oIVsod7ogmswZEzEJwUESpXXIBnMkM4oBi89e3pvid0xCcrmTYnpHOehfCXeJMI9ltyKGBk/lg4Qmt4vKx0YON5yZ83Fz3cjcJW9iDms4d2VwCAwiPtJXYpWx1LYX+cDE0VcTVv+jaKyHhWVdZ3+cIusbg/HA6hNXVNWU+UCC+Le0PG+OJPlUkYnTaEz3EwGOuejfVlJYQPhOLlKKK+L6MsUl9Ppa+wCnmSMQESL4Yr1PS7N5hafMkWf5VlqM4Woxvz0ecJMZCCtjVC/wD00fgR+dHmZPOj4VIiKI3fwHN6jWdOX5ZgWeXtUPcvHAY/ILS6sMWILUeLXqyVPJEjCznwuYjwHci/u/FYRym3apl6i2zWjo2chIuTOf/ul4w6pNsM1z4JQjfB67zMJ4Z1VuK69NAnR8VuNeb5WEuETG9+Z8Hs9/6/GL3fAqdCANt6usV8cN/z91Uq0Fl2veUPdi9hOUhW+eaVJj8/7nUcvyvhuZPVfMb67d4N7EjChrP880bdaS50cL98v0rqtMX7wn7rjnK1B2RDILNB1xoALtjpYSDhhsNfd+SnFmnozsrKZQ0KE5q5Aadp2+QoyTraY8of8rbP+sXrgNyWE1VLSXCWCmyIY7fB8IUk3u2K8e44N7aLY8IMlYlhAekTLQciLWUQXEO8dc5m
  template:
    metadata:
      name: synology-csi
      namespace: csi
