apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.18.5
    
    - repoURL: https://github.com/andyfoston/k3s-deployments
      targetRevision: HEAD
      path: misc/sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
