---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: k3s-ingress
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCvV+Appx1hhbUSjVvOkOP9jT/KQwrCGYaaZFuli80uHGMBUvjBY4YljVO0YssyUlFs/ffvs+BAZnEf3lvJ//JNaZhmceeestJZNe1JkJyIO3pdy/WM8HRj2UJlMl7gKDWERj8zUbMdYmPrxkNH6FkY1aCneHpxhiNYqZO2Mab8GG9pNRDspJSiNSE0f2S3JJ3bKGA7zTyrVWGAyR4ittojKt9hF+4XvGL4kN9dIVNEqjpfNsKUzLU/86bmalke0Qs3JwEs9ctPpaaE2UV6t0c//TcQTDgU0WZtumdvRpNEdmYZtX8EtouVLKakXSxUEj6PJ7DXFBL0PmX0RpYN+l1pm5DR4V1VqSSIVUauXgNgD9h12YQ7vE94+09rDkS/WwSvdya76Aim/Woi37HMgKjTjNb9n8XPAhUmZUA4M40H2qjdwEvD6bE2d2j/Jzlg6Y29kPggftsAUnILIcgiRPi7Sy7YxbxJQYFgQ9TKLNF9IB4TE6WQsNgDD7SoAvf6b4TvnrBtcsCOndVglpy+hDsGuHl1MyEifmrK4B04RODOKGBypWqOCAEFd2MrdqlcSy0xFMGSqqE1KaThYuSnAo3O1kln6/py8evyewdkabTdw794RyCvHaOLE+FKW82e+NDgOe8/9rvrNuOJkG0F284UNjsg6bnPf5IUn/xei1Od+qdpSerk1sZzTa9m2SPg/YRjGgdPhz5sk/Sr+sJ7ER30WcdSLrT2AiAqX5JkQumRSm1wbfOEQvXO4CfqCPYzSTBALx9/3qLCaKRUHpH9n+Di/Oap0ONv1Y+/hENr/9KRzFzUN3fjdjms0/RcwsDUQ91RInOFCnYf7Zv/tBajXe02NhlOeIwTBLjtcgPJrioqpfW/CWicH0KDs+5u8XBa17wnxXHa59BqtH3juRMDneAjoIftuBJFMb4H8Qllw3A+Jw87
  template:
    metadata:
      name: k3s-ingress
      namespace: cloudflare
