apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andyfoston/k3s-deployments
    targetRevision: HEAD
    path: misc/cloudflare
    kustomize:
      # For older Argo CD versions or as a fallback:
      commonAnnotations:
        "argocd.argoproj.io/sync-options": "EnableHelm=true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflare
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
