apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andyfoston/k3s-deployments
    targetRevision: main
    path: misc/cloudflare
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
