---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-registry
  namespace: nest
spec:
  encryptedData:
    .dockerconfigjson: AgC36xDF5Pyt+5RmIZNljlkLmh/YiMPWucMkeHtn0Kc5+fysicXWYWSkd9Nrk3YWO7AzsoKNIzVPK/SrbQqnYDzQIhBOaIIGQoocbqpkqWALw5ffELzcwq98SNUr5kgZ4bd2AWf3K8gHrE9cO8jHBHfk+P6P+VxqP6ADO1JNUiXC+QHB0Y17fYCx0ugOumxrKns/4c0xhwczD18VLg3PvHZorBOwtc1U9VJhlnvITnmPIk0OGmPv9PynZd7EoI53xvpgDg+G/jxWXh+TT4shMKBEZloQy87Tha8G7ydR3mlO70A/7IGPgEr2zYhooX4HdVyrR0SEJ/foM0deCA4vRq+kEIApwbkJYiULz0VeuvRfWfz1oaTeAOEfkAKKMqIEkx2tQQ1CCGh2g34RKKYI8YtllWU7TBgVOUTWhLwt8HJ7fUI7nfo+fXIn/qDQV+Qs1zSFKiHAod+5rsVMPsJz1dQWkWrrRma+SuEedcmoVFwCMZpbfIsckdrAOiQ1yxfs6jUSeuhpnPgMpIPxY7Y8os0kEoLHdbx1BdRKw1LQmYA/cKiFvI4yNjjES2SsJAt3LALt5kDG58bgPL7hxpPBC94UxnI2FMYLV2iZV0Y7tWbsvvxQWfClXn1BCryrWW1m/MiQOMhBiYhX12urPp8NGOLMA1LkfTlWuejKwZP8gL6FrUKGTO+6wChCRxo0hIyXdBxuHK1gaxIodQIs0BjVVJxfM2k3bGLVSgkiMotzL9oZ9ET1gZ6dN660ZiIklWnME1jTz54FrqDHXhjDp13FtvkNJKPHzWCC2n+weu6z1LtsYC8lbqIvvB6YqejhfA3unuIw+iAnBcVRzHZ0bA2vNwYrXVwbWBQopqGcTnnTFOQD3Bj2FiQs51T9YFU8AA786SnMIW3tY/iSG6/COO4xDtBaatGdbRP/b8KtkbvQlF++gdYqqJlBZtXB91wMf2qpJ4TaQSvPUVYmzpqj4yM=
  template:
    metadata:
      name: github-registry
      namespace: nest
    type: kubernetes.io/dockerconfigjson
